### ISSUE TITLE
downgrade patchef version to 0.17.0.0

### ISSUE THREAD

**Issue by aricwang88** [eclipse-velocitas/vehicle-app-python-sdk#54]
### What happened?

vehicle-app-python-sdk/tree/main/examples/seat-adjuster)/Dockerfile

Please downgrade patchelf in  SDK examples code.

### Operating System

macOS (Default)

### What release version or branch did you use?

main

### Relevant log output

```shell
core dump when run staticx.
```

### Code of Conduct

- [X] I agree to follow this project's rules for contributions

**Comment by MP91** [comment]
Hey @aricwang88,

could you please elaborate what you did exactly. We need to be able to reproduce the error.

Thanks!

**Comment by doosuu** [comment]
> Hey @aricwang88,
> 
> could you please elaborate what you did exactly. We need to be able to reproduce the error.
> 
> Thanks!

From reading through the issue, I expect this is the same thing we have already fixed in the template. 
`patchelf` got a new release which is incompatible with `staticx` in the Dockerfile of `seat-adjuster`. We need to pin the version of `patchelf` to 0.17.0. Furthermore we also need to pin the version of the Python base image we are using for the Dockerfile since there are also some incompatible upgrades of the installed tools.

**Comment by aricwang88** [comment]
@MP91  @doosuu ,  exactly correct!  Thanks! I found only in sampleapp example updated, but when import-example into template, it still have problem.  I known the work around, just keep this information for other users. Anyway thx!
